### ISSUE TITLE
Socket response isn't a correct json

### ISSUE THREAD

**Issue by agarasul** [investaz/android-recruitment-test#2]
Socket response isn't a correct json. And what all this data is mean? Can write name of this instead of 1,2,3 and etc.

**Comment by agarasul** [comment]
Still isn't correct

**Comment by zvonchuk-investaz** [comment]
@agarasul To work with a web socket, you need to use the socket.io library.

Try https://websocket.org/echo.html for testing.

Example of answer :  https://pastebin.com/H7S7ivxZ
